[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/webhook-generate"
  to = "/.netlify/functions/webhook-generate"
  status = 200

[[redirects]]
  from = "/webhook-regenerate"
  to = "/.netlify/functions/webhook-regenerate"
  status = 200

[[redirects]]
  from = "/cors-proxy"
  to = "/.netlify/functions/cors-proxy"
  status = 200

[[redirects]]
  from = "/n8n-webhook-proxy"
  to = "/.netlify/functions/n8n-webhook-proxy"
  status = 200

[[redirects]]
  from = "/n8n_binary/n8n-to-url-converter.php"
  to = "/.netlify/functions/image-converter"
  status = 200

[[redirects]]
  from = "/test-webhook"
  to = "/.netlify/functions/test-webhook"
  status = 200

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
